title: "Genos"
description: "Grupo de Pesquisa em Computação Musical"
#url: "https://genosmus.com"
#url:  https://kroger.github.io/
#baseurl: "/genosmus"
google_analytics: "UA-25220567-1"

timezone: "America/Bahia"
markdown: kramdown
#theme: minimal-mistakes-jekyll

remote_theme: "mmistakes/minimal-mistakes@4.27.3"

plugins:
  - jekyll-include-cache

exclude:
  - img
  - .bundle
  - out
  - marcos/cronogramas
  - "*.bib"
  - "Gemfile*"
  - Makefile
  
include: ["_pages"]

atom_feed:
  hide: true

footer:
  links: []
  