title: Genos
description: "Grupo de Pesquisa em Computação Musical"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://genosmus.com"

# Build settings
markdown: kramdown
theme: jekyll-whiteglass
