title: "Genos"
description: "Grupo de Pesquisa em Computação Musical"
url: "https://genosmus.com"
google_analytics: "UA-25220567-1"

semestre: "2018.1"

markdown: kramdown
exclude: [.idea, img, vendor, .bundle]

collections:
  pages:
    output: true
    permalink: /:path
  pedro:
    output: true
    permalink: /:collection/:name
  marcos:
    output: true
    permalink: /:collection/:name

toc:
  min_level: 1
  max_level: 2

plugins:
  - jekyll-toc
  - jekyll-last-modified-at
